
# Dockerfile for server
FROM node:20-alpine
WORKDIR /usr/src/app
COPY server/package.json ./
RUN npm install --only=production
COPY server/ ./
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node","index.js"]
